### ISSUE TITLE
Cannot find module 'objtree'

### ISSUE THREAD

**Issue by mukeshzt** [rranauro/ObjTree#10]
I'm new to nodejs and working with sml to json parse. I'm using your nmp package but its showing 
module not found.
Here is my code.. 
```
var ObjTree = require("objtree");
var xotree = new ObjTree();

var objtree_xml = '<?xml version="1.0" encoding="UTF-8"?><family name="Kawasaki"><father>Yasuhisa</father><mother>Chizuko</mother><children><girl>Shiori</girl><boy>Yusuke</boy><boy>Kairi</boy></children></family>';
var xotree_out = xotree.parseXML( objtree_xml );
 
 console.log(xotree_out);
```
Its display error with 

$ node xmltree.js 
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'objtree'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/boatapp/xmltree.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by rranauro** [comment]
If you are just running from local directory, you provide the full path to the require, as in:

```
require('./ObjTree');
```

When you install as a package in your /node_modules directory then node will use its path rules in that case use

```
require('ObjTree')
```

**Comment by rranauro** [comment]
I updated the Repo with latest pull request. 

``` 
var ObjTree = require('objtree')
```
Should work fine now.
